[[server]]
	name = "jopaserver"
	port = 8080
	host = "127.0.0.1"
	error_page = "error.html"
	body_size_limit = 10
	[[location]]
		location = "/"
		root = "/var/www/html/jopa.html"
		methods = ["GET", "POST"]
		directory_list = true
		directory_fallback = "its_a_directory.html"
	[[location]]
		location = "/secret/"
		root = "/var/www/html/secret.html"
		methods = ["GET"]
		directory_list = false
		directory_fallback = "oops.html"

