[[server]]
	name = "pohek1.org"
	host = "127.0.0.1"
	port = 8080
	body_size_limit = 10000000
	[server.error_page]
		403 = "www/errorFolder/index2.html"
	[[server.location]]
		location = "/"
		root = "www/"
		methods = ["GET", "POST", "DELETE"]
		autoindex = true
		directory_file = "index.html"
		upload_accept = true
		upload_dir = "/var/www/html/upload"
	[[server.location]]
		location = "/images"
		root = "www/images"
		methods = ["GET"]
		autoindex = true
	[[server.location]]
		location = "/images/168.png"
		redirect = ["301", "http://127.0.0.1:8080/168.png"]
	[[server.location]]
		location = "/errorFolder/images/168.png"
		redirect = ["301", "http://127.0.0.1:8080/168.png"]
	[[server.location]]
		location = "*.jpeg"
		root = "www/images/jpegImg"
		methods = ["GET", "PUT"]
	[[server.location]]
		location = "*.png"
		root = "www/images/pngImg"
		methods = ["GET"]
	[[server.location]]
		location = "*.ico"
		root = "www/images/icoImg"
		methods = ["GET"]
	[[server.location]]
		location = "/errorFolder"
		root = "www/errorFolder"
		methods = ["GET", "POST"]
		autoindex = false
	[[server.location]]
		location = "*.php"
		root = "www/script"
		autoindex = false
		cgi_pass = "/usr/bin/php-cgi"
[[server]]
	name = "pohek2.org"
	host = "127.0.0.1"
	port = 8081
	body_size_limit = 10000
	[server.error_page]
		404 = "error_404.html"
		405 = "error_405.html"
		406 = "error_406.html"
		407 = "error_407.html"
	[[server.location]]
		location = "/"
		root = "second/"
		methods = ["POST"]
		autoindex = true
		directory_file = "index.html"
		upload_accept = false
		upload_dir = "/var/www/html/upload"
[[server]]
	name = "localhost"
	host = "127.0.0.1"
	port = 8081
	body_size_limit = 10000
	[server.error_page]
		404 = "error_404.html"
		405 = "error_405.html"
		406 = "error_406.html"
		407 = "error_407.html"
	[[server.location]]
		location = "/"
		root = "second/"
		methods = ["POST", "GET"]
		autoindex = true
		directory_file = "index.html"
		upload_accept = false
		upload_dir = "/var/www/html/upload"
