[[server]]
	name = "pohek1.org"
	host = "127.0.0.1" # check inet_addr()
	port = 8080 	# check num, (0, 65536)
	body_size_limit = 10000000 #(pofig and > 0)
	[server.error_page]
		"404" = "www/real/errorFolder/error_404.html" # throw exception if not string
	[[server.location]]
		location = "/" # mandatory
		root = "www/real/"  # check valid
		methods = ["GET", "POST", "DELETE"] 
		autoindex = true #check if bool
		directory_file = "index.html"
		upload_accept = true #throw exception if not bool
		upload_dir = "www/real/upload" # check valid
	[[server.location]]
		location = "/images"
		root = "www/real/images"
		methods = ["GET"]
		autoindex = true
	[[server.location]]
		location = "/images/168.png"
		redirect = ["301", "http://127.0.0.1:8080/168.png"] #throw exception if no array, or more 2 elem, or elem is not str
	[[server.location]]
		location = "/errorFolder/images/168.png"
		redirect = ["301", "http://127.0.0.1:8080/168.png"]
	[[server.location]]
		location = "*.jpeg"
		root = "www/real/images/jpegImg"
		methods = ["GET", "PUT"]
	[[server.location]]
		location = "*.png"
		root = "www/real/images/pngImg"
		methods = ["GET"]
	[[server.location]]
		location = "/errorFolder"
		root = "www/real/errorFolder"
		methods = ["GET", "POST"]
		autoindex = true
	[[server.location]]
		location = "*.php"
		root = "www/real/script"
		autoindex = false
		cgi_pass = "/usr/bin/php-cgi" #check valid
[[server]]
	name = "pohek2.org"
	host = "127.0.0.1"
	port = 8081
	body_size_limit = 10000
	[server.error_page]
		404 = "error_404.html"
		405 = "error_405.html"
		406 = "error_406.html"
		407 = "error_407.html"
	[[server.location]]
		location = "/"
		root = "second/"
		methods = ["POST"]
		autoindex = true
		directory_file = "index.html"
		upload_accept = false
		upload_dir = "www/real/upload"
[[server]]
	name = "localhost"
	host = "127.0.0.1"
	port = 8081
	body_size_limit = 10000
	[server.error_page]
		404 = "error_404.html"
		405 = "error_405.html"
		406 = "error_406.html"
		407 = "error_407.html"
	[[server.location]]
		location = "/"
		root = "second/"
		methods = ["POST", "GET"]
		autoindex = true
		directory_file = "index.html"
		upload_accept = false
		upload_dir = "www/real/upload"
